######################################################################
# Automatically generated by qmake (3.0) So Feb 15 23:39:00 2015
######################################################################

TEMPLATE = app
TARGET = ircbot
INCLUDEPATH += .

QT += network

CONFIG += c++11 console

# Input
HEADERS += src/Network.IRC.Server.hpp
SOURCES += src/main.cpp src/Network.IRC.Server.cpp
